name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: plugin
          name: sms
          description: "A plugin for Home Assistant that allows you to send and display SMS messages"
          url: https://github.com/jpmchia/ha-sms